# Project information
site_name: Apuntes de eduardofilo
site_description: Apuntes varios sobre algunas de las cosas que necesito recordar, principalmente sobre Desarrollo y Sistemas.
site_author: Eduardo Moreno Lamana

# Repository
repo_name: 'eduardofilo.mkdocs'
repo_url: https://github.com/eduardofilo/eduardofilo.mkdocs

# Configuration
use_directory_urls: false
plugins:
    - search:
        lang: ['es']
theme:
    name: material
    logo: 'images/eduardofilo.png'
    language: es
    feature:
        tabs: true
    palette:
        primary: 'deep orange'
        accent: 'amber'


# Customization
extra:
    social:
        - type: github-alt
          link: https://github.com/eduardofilo
        - type: twitter
          link: https://twitter.com/eduardofilo
        - type: linkedin
          link: https://linkedin.com/in/edumoreno/
        - type: tumblr
          link: https://eduardofilo.es
        - type: youtube
          link: https://www.youtube.com/c/EduardoMorenoLamana
    search:
        language: 'es'
    manifest: 'manifest.webmanifest'

# Extensions
markdown_extensions:
    - codehilite:
        linenums: true
    - toc:
        permalink: True
    - admonition

# Navegación
nav:
    - Blog: index.md
    - 2019-01-26-conversion_apuntes_mkdocs.md
    - 2018-10-20-Octoprint-en-Anet-A8.md
    - 2018-10-19-crankshaft.md
    - 2018-05-05-otto.md
    - 2017-01-14-raspi2-kodi-16-tvheadend.md
    - 2016-12-06-raspi3-kodi.md
    - 2016-10-17-raspi-switch.md
    - 2016-08-17-el-mundo-de-ayer.md
    - 2016-08-02-stm32-vl-discovery.md
    - 2016-07-21-PIGRRL-2.md
    - 2016-07-10-wild.md
    - 2016-07-02-virus-android.md
    - 2016-04-10-un-antropologo-en-marte.md
    - 2016-02-25-los-innovadores.md
    - 2015-03-14-raspi2-kodi-tvheadend.md
    - 2015-01-09-moviles.md
    - 2015-01-08-jekyll.md
    - 2014-12-26-dokuwiki-raspi.md
    - 2014-12-20-micro-placas.md
    - 2014-12-15-presentacion.md
    - Cursos:
        - Phonegap: cursos/phonegap.md
    - Desarrollo:
        - Android: desarrollo/android.md
        - Bases de Datos: desarrollo/db.md
        - Diseño: desarrollo/diseno.md
        - Dokuwiki: desarrollo/dokuwiki.md
        - Eclipse: desarrollo/eclipse.md
        - Gestión de Proyectos: desarrollo/projects.md
        - Git: desarrollo/git.md
        - HTML+CSS: desarrollo/html.md
        - Java: desarrollo/java.md
        - JavaEE: desarrollo/javaee.md
        - JavaScript: desarrollo/javascript.md
        - Joomla: desarrollo/joomla.md
        - PHP: desarrollo/php.md
        - Python/Django: desarrollo/python.md
        - Ruby on Rails: desarrollo/ror.md
        - Spree: desarrollo/spree.md
        - Sublime Text 2: desarrollo/subl.md
        - SVN: desarrollo/svn.md
        - Vagrant: desarrollo/vagrant.md
        - Yii: desarrollo/yii.md
    - Proyectos:
        - Headset Commander: proyectos/headsetcomm.md
        - Impresión 3D de ecografías: proyectos/dicom.md
        - Minecraft: proyectos/minecraft.md
    - Sistemas:
        - 3D Printing: sistemas/3d_printing.md
        - Android: sistemas/android_system.md
        - Aplicaciones interesantes: sistemas/soft_imprescindible.md
        - AppleTV: sistemas/appletv.md
        - Bus Pirate: sistemas/bus_pirate.md
        - e-mail: sistemas/email.md
        - Emulación: sistemas/emulacion.md
        - Impresoras: sistemas/impresoras.md
        - IOT: sistemas/iot.md
        - Kodi/OpenELEC: sistemas/kodi.md
        - Mac OS X: sistemas/macosx.md
        - Mandrake: sistemas/mandrake.md
        - MySQL: sistemas/mysql.md
        - NAS: sistemas/nas.md
        - ODROID: sistemas/odroid.md
        - Office: sistemas/office.md
        - Raspberry Pi: sistemas/raspi.md
        - Redes: sistemas/redes.md
        - Router Xiaomi MiWiFi 3G: sistemas/router_xiaomi.md
        - Ubuntu Phone: sistemas/ubuntu_phone.md
        - Ubuntu: sistemas/ubuntu.md
        - UNIX: sistemas/unix.md
        - Windows: sistemas/trucos_windows.md
        - ZX Spectrum: sistemas/zx-spectrum.md
        - ZX-Uno: sistemas/zx-uno.md
    - Varios:
        - Bicicleta: varios/bici.md
        - Electrónica: varios/electronica.md
        - Enlaces: varios/links.md
        - Inglés: varios/english.md
        - Opel Corsa D: varios/corsa_d.md
        - STM32: desarrollo/stm32.md
        - Viajes: varios/viajes.md
